name: BlockedInCombat
version: 1.1.2
main: fr.kinj14.blockedincombat.Main
api-version: '1.21'
author: kinj14
description: Plugin blokujący budowanie podczas walki.
commands:
  blockedincombat:
    description: Główna komenda pluginu.
    aliases: [bic]
